# clears the cache on dromzeh.dev for every push
name: Deploy
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        steps:
            - uses: actions/checkout@v2 
            - name: Wait for CF Pages # waits for CF to finish building
              id: cf-pages
              uses: WalshyDev/cf-pages-await@v1
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN  }}
                  accountId: 'ba4e8f7f9ffbc23dba6acd0d9bd3ef46'
                  project: 'dromzeh-dev'
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
            - run: | # clears cache on CF
                  curl -X \
                    -H "Authorization: ${{ secrets.CF_API_TOKEN }}" \
                    -H "Content-Type: application/json" \
                    --data '{"purge_everything":true}' \
                    https://api.cloudflare.com/client/v4/zones/ba4e8f7f9ffbc23dba6acd0d9bd3ef46/purge_cache
